-   id: ngtest
    name: ngtest
    description: Runs ng test
    entry: ngtest.py
    language: script

    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
